---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 1h
  target:
    name: prowlarr-secret
    template:
      engineVersion: v2
      data:
        PROWLARR__AUTH__APIKEY: "{{ .apikey }}"
  data:
    - secretKey: apikey
      remoteRef:
        key: PROWLARR_API_KEY
