apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
type: Opaque
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:NrtT0wH/zNY1TQolBQyJihaPU5m7KMJrdMo3CqBQYO0=,iv:KNpcTiAvo6usmXXET9hF82Ww26yKIJvjZgt+duKwlRs=,tag:sTxIlpsINCV8y6Bsidu78Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYm1LMGNxa2xBZWhaeS9t
            N2dBVnFxT2tqRUtkVGowS1dyVHlzS2VUZVVrCnduWFA4STM3SjRQUld0dy9QRjVY
            MzJ6VEg5cWQxOXpqUzFiQ3AwMnZUTG8KLS0tIHRqTnRGRk9qaysrekR1c0lxUkNl
            TlMvaUhJY01VQ0VpQkhlSHE3anJKQ0kK/n7kFYRpDETXMvO/QDSDpF/3HkR1f5Qp
            FbLYFTFoKAycCl3jHUOXN3hQXEyCgG2sTzFyDOTKQTGD0ZKsWdUbAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14h4tdg6ftww8xgyrg2wrgqetkkf7deevd6azf65mhcld863jx4dsv3grx7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T14:22:44Z"
    mac: ENC[AES256_GCM,data:tQYGPMvhE8ytTuGQJhYSTvFdWCRnvdN9/Hp6ufHyTTlB/KQBsw+VUsNcICOyYY/Z6jAj1XuaetFUFSNnSNVbwRObG4qI34/F2T1XWYc3VjL0MnATateSJurN+gQ8gBiiuJemC06/j9sAlQTxhPfOpHDb1mX4P3/ip4yQz6bCbog=,iv:/2uMC2OvxTWEwuVAYecxoNXozSxzIV+pzorSz4LElOI=,tag:TKsJfbg/dQhOkCeZ6xEfsQ==,type:str]
    version: 3.13.3
