apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:BwDlERE=,iv:RhIwLwxJO6r8xRwwDKpp44aWBuBf1LwI6KtT0tzA+Ww=,tag:dZij3CsFhePjakaE5fHsGg==,type:str]
    admin-password: ENC[AES256_GCM,data:e1uFK+lvBnIA2ljyo6EMbEg1UpUqo68u,iv:UJwpDB5UgOKNKy/H2ecewPN/FbJ1oZq9YyrMyk5STjo=,tag:sGROsk8o6YHz5rqhrGLzsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3anVPNWh2NWxwbENOaE5h
            blNJczFJcjcxN1pqVkZpeHViejN0WjJ0MUFnCmZJSGpXYXJ6VFUxZlNHc2VSbkMy
            SlF5Y0hYTUJlZDd0VnpzREdzQVhyeFUKLS0tIERTL01oemdPRkZ4OTJlWDZJajNo
            c1VQR3NlVlpVcFVpQkMvNHdoTm9Fb0EK8ZenlODvB9ehLGwNaDNJt1IVG6YQceX3
            PdDZc7reXMxjLNbZV6RFA+DODzlSK22TKHFP/BvNBizKJsS0YN2Krg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14h4tdg6ftww8xgyrg2wrgqetkkf7deevd6azf65mhcld863jx4dsv3grx7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T19:55:32Z"
    mac: ENC[AES256_GCM,data:Jo2AnsIg/zGMYOEAVkiO+ybRzQ++ENSetCivjH0Uvg/+gXx2xuvLS8+n5180RbL+Uz2ZWJNM/f5Nml17IAyek13C2GoJ/zoMX7eDA1pfwQXLkCKlAweUtP47oGYwXiCqgkHaf4OJu8FScfc7YpHuhX0fIgXm7wxLVZ5oq9ci4bo=,iv:qxf97bVvrixYZY69p1gY41tAb9zqvj2SX5dmyv6Hpts=,tag:V7lxvFBYMITmt4V6Bpol7g==,type:str]
    version: 3.13.3
