---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ./resources.yaml
configMapGenerator:
  - name: local-path-config
    files:
      - config.json=./config.json
      - setup=./setup.sh
      - teardown=./teardown.sh
      - helperPod.yaml=./helper-pod.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
