apiVersion: v1
kind: Secret
metadata:
    name: newt-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:LF5u356OEKpTQkcgprngm368UtqnVD0/aAT93kISLtegaEdSFvn91p4GfitfsdH5lv3s7n7O+NhjeTgwuUHbKA==,iv:9euEV6SUZZEjhCPWF2hIILBMUtHHjg1M2EVJMPf0vNs=,tag:0f7C2WwmgoqDb3sGgR6txQ==,type:comment]
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:3PjWjoxp0OuN7TmBHxqCzO8KKdacAyZ39i2EvA==,iv:IQK4dfxjCEKLd0qEfEmVh2DYBEjS/U/DrYmHXNzjhsk=,tag:Z9VTK5o05flOkQ1po8bgUw==,type:str] #ENC[AES256_GCM,data:Vm5lzdI=,iv:5ul9FuRB+36guhK2cN9aXhJPsoDmZSV43B4J2pv6QRM=,tag:40RWFXjfvVjR6I1vCsvauQ==,type:comment]
    NEWT_ID: ENC[AES256_GCM,data:VBxYTDvNlADBPA==,iv:KFL32PVxwUvCoZls98AwgXb0h9Fl1Ogntkuz/WQOhVg=,tag:LJB8QhybX/jU40Pmo+KcRA==,type:str] #ENC[AES256_GCM,data:fPl8SMI=,iv:T0pPaUnCDoK6abLVfiwWipR78uUIUBZ9HmSuCNnwQug=,tag:BKyO7/lk6o/fSlE94j6qsA==,type:comment]
    NEWT_SECRET: ENC[AES256_GCM,data:qt15L5ucVTZcWA==,iv:DJQYXZH8smW7Ec7/InWPNOJY3OFQuH/cL+qe/q7PYrk=,tag:2hqyGypSG2p8ruz7HJDR4g==,type:str] #ENC[AES256_GCM,data:wv5ERdQ=,iv:kUqudqxqo8s9t/Mg1ZQt0FSquJ/hSz0PcA5YEgriV5g=,tag:p3lkZJyWCqdfVEs4zE9zPA==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MnF2Q28yZDgyUU1MaG5B
            OCtBWlpma1MyTVk0YkxOR1M3SnNIdlRTVVRVCkM4ZmhjVHA2MTNxT2RsMlVxbUc2
            blhrdk91Y0NFZWM2THBBZXp4Z3pVa00KLS0tIGV0QzFnKzc3aGFFWE9sclIxcU9H
            bmhYYWJqRkFyOHZNNnBaYVlMWVRmZjgKxY9TnPU5QBcAmiNAOu3/doVTKJRycP0+
            8ITpXDMheGRf4hUFURhJxQQJ4Jugz2sWaI2wH8qIHXimW1DIL7VB+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14h4tdg6ftww8xgyrg2wrgqetkkf7deevd6azf65mhcld863jx4dsv3grx7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T14:37:17Z"
    mac: ENC[AES256_GCM,data:qNnl5buPw1pgIbVL5l3QVDzmYMqd/mOqKXHj+EOcc3vz9G7xWZcnNJBD9ry1cGO29mpJvMtVl17ESgsifeWldhtjMgDR6O0jPWTxQ/jG8dolnTLYmVo9ctYA2U8sISB5ueVEHyuCuLuJ8A/psOUIbah6h5jSCd4CpLL1yM2TG6w=,iv:ZTc3ZlM5yfOUQSceCltc0uoFCRAZwdcVltB17qipZsM=,tag:zpzUPrGAyYFHHby4N0G11Q==,type:str]
    version: 3.13.3
