apiVersion: v1
kind: Secret
metadata:
    name: newt-secret
    namespace: network
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:iAaQLVtbQgFBxqj2r22G14PDwOV5KQKvLogl,iv:RTzODb/Y3JjzPIThIOkIbZtKjPi5fLr1Ni8BuiQFZQY=,tag:sdFBNbj8WPs4J1CYiA5y0A==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:BLrm888eIDy+d6Yo2Dqi,iv:qOZYpZZrWGfMlBT4SWnofqBzT7yEef7FGWkHRHVMNj8=,tag:f3BYaVjm2SK8h+HaMv++OQ==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:zGq3QRFQddwYqpWDEsqibxAshThCBfcah2WaXa/aDn77mwXlvdydIpyBK1EOes6I,iv:OXqxt8DM0caaJmX9LfYGM007iYTuwn7OLMHIxrUfbrE=,tag:dA9vbA+j/SLvtmza45s6qQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N2wzdkd1S3dnYTFNMVNE
            SW9JVnlEdkhFQnhIL1JPTW9Vdkg0aWdzTG04CmQ1VVFkYnJRQ0ZyTEdPZ0VaQWJl
            czhiTlh1ZFovZWF6b3RPTEtaVm43ZnMKLS0tIGpEOTBVU2NRWFRTbnA3YWk1aXFp
            WjVsZTRuaUtYRWVINVFNYnl3K0hIME0KbW57Av2F41JXc0VvbDXvVnpVxRQPK/is
            62h17u095Lb+86ghAQeSSWOuj5s8GxSZV403lkKdV5EyUKVJFNSjbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14h4tdg6ftww8xgyrg2wrgqetkkf7deevd6azf65mhcld863jx4dsv3grx7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T00:07:06Z"
    mac: ENC[AES256_GCM,data:nN0LCrjX4A7oXlY71hdi/VR7S3Rz/ho8z0lVG+wdO8Re2U/d+abOlL4Bv3FUmWcV/X9wMkBTRcG8pqxzd6xo3Di4Ev4DFHW6IdRhqEZX0yZo+yaBSVyiiLE1aCpMvONaztdUAYHGDWPkak/5whSPvbi6p2zUmgCDWQ5JNEqze68=,iv:emQJayC7P0/kEwhh01JL4cUAr4EwFQvRUe9gHSMaF/E=,tag:APbcRkS5oo0wtvywqKMNog==,type:str]
    version: 3.13.3
