---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 1h
  target:
    name: cloudflare-dns-token
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARE_DNS_TOKEN
