---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 1h
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        RADARR__AUTH__APIKEY: "{{ .apikey }}"
  data:
    - secretKey: apikey
      remoteRef:
        key: RADARR_API_KEY
