apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:GHyaNV1s9HBV90dYJj2FRYWA4TL/jwryQW3R6wej86g=,iv:MtMCMUPo1+zlv1dckrtNbrKfP/tHPrXvYwxz0ZqUwyg=,tag:6+HyzebjsttB4m8R48kryA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMXBvL2ppS3A0TnRHcElG
            S3Q4SkpXTkFvNHZ1QVpHNTNkUEZYUktuY1V3ClR2eXlpMmZWTW9KWm5pN0ZhaFIy
            SXRkTUR3Y2xvaTdGeG9Tb1U1aEh2ZmsKLS0tIEtFYUI0bWtjdXFoNEoydzNhdXZH
            cDhEVWE1dXlDeTNsRWsyRWZKcHJxdjQKOSH6lzZhHAgDNeqepiIXCNMFhXWlZ6jx
            Bl2PtezS4NMkVT+eeE80FNbdLK/Vj8HBdbLyqNDkHf2wCkmuPt8/sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14h4tdg6ftww8xgyrg2wrgqetkkf7deevd6azf65mhcld863jx4dsv3grx7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T14:22:44Z"
    mac: ENC[AES256_GCM,data:gl0KC+CLJvGexUwqgQPNpgvmICjvM9LHoW0Fhit6W55JV5d9XPzslZ0q2qSQaWNIOyKt3PcuIJSJr59IdSBM4kVJJMKF/qLFzm/+CLo5bMA07r7vCoiDPrFkLSLXQwiQyhi2Lc3RMYLfuLdCFrkiX+F6xH0hLnD4WXrSy8+8XtU=,iv:jB/gY841Ew66OmacECQTUSZ8DTN/M6GVKhWXwvivnL4=,tag:j7wX+faV5zjpC9cJXf/7XA==,type:str]
    version: 3.13.3
