apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:MdOOlQ1y6r2O2ESFVlnV/X4Fs621CQtOtBbej5HZ/SQ=,iv:TTtILtYDA/oIfRaB4ymCqdMC7agwySzqMg2XSfggCjo=,tag:Dg8KRnOwx4cM/2G6v8l16w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUkpiOGtzbUpIWnFoRWNM
            bEJXVCtXTEEzUkt1bXN6bzgralBMUDkrZWp3CkNreU5SZldFQStpZ2RXSlZHYW1Z
            UXlOMDdKUEpxeVJGSlE3SzlLdGZMbUEKLS0tIGZGMzJaU3hVc2Ezb3UzbkI0OGsw
            S0NBeEVyeVlCdG94N1VEU2NiaFBYYkUKAYVXjOyTHgrw4MU3ohJXW1if+jG7Blwr
            E5Ojc92kXyBVLEcITYQ6l8774YIjHo/6vmucUQBBrHHJRaUfBrKJlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14h4tdg6ftww8xgyrg2wrgqetkkf7deevd6azf65mhcld863jx4dsv3grx7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T14:22:44Z"
    mac: ENC[AES256_GCM,data:1aCM4qciUwIUOKnrlB+MyloceUEvflfuvecNj2GjvWD24aRNullFcaYFr/GH+y2h+ohBOf+F0daxcOK7hiFHtztOiLsGTATV4EngBuY4on4yPa7qvsHqE3H2mVf/Ml8a1+uuCoa2UeSPNmdxhrYf7e6l5D8ojpfTMqZyoH/2gZE=,iv:7mhVCMWmnJWEpnqdrfsiN4U5tmwBnxHd8F6AJStNLQ0=,tag:jJEqoYQnBToWolqLzPtlOQ==,type:str]
    version: 3.13.3
