---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 1h
  target:
    name: recyclarr-secret
  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: SONARR_API_KEY
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: RADARR_API_KEY
