apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:82lyV8E6HtyxEIDkPoPT7w7qA6qVx1tZf6oTatCWYPI=,iv:uUMKS+9sblIWbSOIzXesUS/uzwSo0HGwbPa1VmU8FxQ=,tag:88wpvyaKczyMufPKkbg6xQ==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:jlh5sHdR4D1pZecjKPxhvsqrl3pwsQuZw3DtYpxo80w=,iv:yeT54O70qk1gNtZKHPSg2zs8PpbU+Vfmbe+YGC2udJM=,tag:B9bEIGl9YT63gVh1bpH4+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUDNkanpNY0ZaZTY5Umpq
            TDFhWUdpczA1NDJYVlZadTdoQUVmeERsYldZClAweFlUdkhVN2NRb21jbG55M2l6
            NlFSVmN3Vzk5aXUxcDdNK29obHRYZ28KLS0tICtyUTY5SGVwQWF2L05ZZTI3Q2dh
            NFpvUFc5a3ZqWjJiM3lTRXpZeWJ6SlUKrGtbYI7Zy836YCU/JFZJT9gx2wjsSSwZ
            C5n275Dzx0zhCJiP+6thkKKJDP4TiZVnPhieyJNBF+KuBpk8EeFGVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14h4tdg6ftww8xgyrg2wrgqetkkf7deevd6azf65mhcld863jx4dsv3grx7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T14:22:44Z"
    mac: ENC[AES256_GCM,data:cN3oCMqeQKWVLVPTzWa+aDNkbanl5lpPTraNHJythlgmeutpUbvvywhJIKp/nchTBb9NLTUMCQe+q1IrBs9s4zVqNlTi8W0qjDIBmnxQaMNTLudAI7qQolZLlh+XFxhe80hi9Ursg6HcYBfT7W/+JEqNzlJ0GZqATbartjFlmSg=,iv:pHtC1Oczj6Nw1/pJiJ1mP01dA964PsAchQzTl2mET3M=,tag:/74sGfVvFLAUxuog7cVHJw==,type:str]
    version: 3.13.3
