apiVersion: v1
kind: Secret
metadata:
    name: infisical-machine-identity
    namespace: external-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:3kcY/q3GC5Ab6GsolvGAAkWEg5S4qgv5Auj0vyMJkK8KYrh/KsQP2YxL5N1EuUM0stD7j0z3eb1H08NQkyIvioV6Ss4mx1A=,iv:8DTN8pumGNMZsuxfFpJ6PO8l/+sehjjNWotMdhye99Y=,tag:wwQq8NEwA2scIK5H1kx76A==,type:comment]
    clientId: ENC[AES256_GCM,data:10WHrBTVGOZqQg==,iv:3+tVC6Ypj8q+r8zyeHESJeM2sGVvhbO8iKvwsO7v6R0=,tag:JTtxHmVND66X0FL64ovQMg==,type:str]
    clientSecret: ENC[AES256_GCM,data:bgGqeKrGFQcAug==,iv:B2+bhavzjJNhXbgADltzWqdq/5y4EeDFv1cXXDmF9FQ=,tag:DgzUFv1u40bwyJitv0ATKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocC95VERuKytRN3o5Y2Jl
            Wm8xcnIwOWFnckhXSEthUVRUdGVzZEwxUFJZCkVySGk4eC80U3FuZ1BtaFl1a2lP
            cVNTYjM0cXp0anRLcER2UHh4cXc0QUUKLS0tIDBwRHpYVkw3TmhUVitKc0NUeGph
            Y3pPSjBKN3NqTnc1NzBva2FSV0VhancKF0jV9ZnvFTbuHxLbDuB+EftPSq1wVaXw
            +dlOerhR1JNgvGzX+rwO6yAMhFWz6bUdd6WmlPzccFaoaEyZR0S1NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14h4tdg6ftww8xgyrg2wrgqetkkf7deevd6azf65mhcld863jx4dsv3grx7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T22:19:32Z"
    mac: ENC[AES256_GCM,data:ujoqOJkEy5SA5/7b9SXTHPIztzgwtHxqOt/z8txorbi4i+jpJw37kmbs3fXy5xoqVMxqCxNlPZcmMx+GEnO8LPOc6Oc1wRBHTYljejsqS4LS3CTxfgQuazPXAcwRtu7cGllrD9vOoboeurSRzVA/wEj/GqspZeFh9I1oayuyc08=,iv:VvvkIBJ5lHbD1N9rQjz/o0X76u5fomIvCAC+OJ5BqaQ=,tag:WOWN2ekPztg/pijtTXnVcg==,type:str]
    version: 3.13.3
