apiVersion: v1
kind: Secret
metadata:
    name: infisical-machine-identity
    namespace: external-secrets
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:w1Jv7HXkAysXOYHFbQsu3pMcGtz3933DEePGOJmclegyQx6I,iv:kxyUhWmM2hR7hIEVh5miSzFu5imQkr/h3kL6AiWEa7M=,tag:T5qJ/xP5dLOvR++lHZuFJw==,type:str]
    clientSecret: ENC[AES256_GCM,data:748Jp5LdwFVtKQ4VVygan0/+xylLsXDIgnT7SuNUi18bqLCpkTvj3lmbkKwkONX56sZmOU+3pYa3oeNA4Nl2bg==,iv:NfmHlaE0VWaFtGm4kjYzMZ5VyUbXGJQHrHfMLtiIbwU=,tag:dP1SFqVbIPBFo+vHp/XbJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dnVHTzJadGVOdmt1dG5o
            TlVQdFA4bDkxMC8rTjRzRWRYQ3oyV1dCUzJBCkVxdUdlRFYyTXpyQmZjS1M4RDBt
            V3FRQUVqcHp3UERZL2U3T05HdFJLWFUKLS0tIFgwUTExdDFpYnVlS1JHZFVrNDIz
            bTF0NE9ialptMUN2UzByb1NLVXpUSncKgk49Zfc+t9BUX1Jc17KebIcExsByj7DA
            G1MHNaYdhR5gyM1O14Hb33cT7lffqXEgnacCZv+Gb2bxRyb4I0fr4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14h4tdg6ftww8xgyrg2wrgqetkkf7deevd6azf65mhcld863jx4dsv3grx7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T22:39:46Z"
    mac: ENC[AES256_GCM,data:JeM3Auiy8gwnI32mnMRm9hQuG8rS7y3bsEbvy1g5kKkg3oJriUrxphunoKtW+zZlH5qBlcnEBKrWUwqsNPcR+eVJPBk80j6l877CFllsrsh6/lg+76rr8W0qX60HulYPvRY84wF+VvhLIpZedS1qT8rt+hBlVZkr0q6b7uVciHM=,iv:HBaBidJ1mqi6fKnB6Qiq19HlrToqF2YfawYorN8gP4A=,tag:F1tdEisWU5oM0H+Aa3xPaw==,type:str]
    version: 3.13.3
